#########################################################################
# Wrong definition of switch/button combo leads to exception.
#
# Device: LilyGO TTGO TO ESP8266 OLED (T12 V2.0)
#         ESP8266EX with SH1106 128x64 OLED Display
#         and three physical momentary push buttons
#
# https://www.tinytronics.nl/shop/en/development-boards/microcontroller-boards/with-wi-fi/lilygo-ttgo-to-esp8266-oled
# https://templates.blakadder.com/lilygo_ESP8266_OLED_SH1106.html

substitutions:
  device_name: "Lab Control"

esphome:
  name: lab-control

esp8266:
  board: esp12e

api:

logger:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Amsterdam

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: $device_name

captive_portal:

#########################################################################
# Trying to use physical momentary push button as an on/off switch:
# a push on the button should toggle the switch

binary_sensor:

- platform: gpio
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    id: btn1
    on_press:
      - switch.toggle: sw1

switch:

# UNCOMMENT THIS FOR START-UP EXCEPTION
#  - platform: gpio
#    pin:
#      number: GPIO12
#      inverted: true
#      mode:
#        input: true
#        pullup: true

# UNCOMMENT THIS FOR WORKING CODE
#  - platform: template
#    optimistic: true

    id: sw1
    name: $device_name Switch
    on_turn_on:
      - component.update: sh1106
    on_turn_off:
      - component.update: sh1106

#########################################################################
# Display

font:
  - file: "fonts/Tahoma.ttf"
    id: font13
    size: 13

i2c:
  scl: GPIO04
  sda: GPIO05

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    contrast: 50%
    update_interval: 5s
    id: sh1106
    lambda: |-
      static int y = 10;
      it.printf(10, y, id(font13), "Switch is %s", id(sw1).state ? "ON" : "OFF");
      y = y == 10 ? 40 : 10;
